/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloJNI */

#ifndef _Included_HelloJNI
#define _Included_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloJNI
 * Method:    getCpuInfo
 * Signature: ()Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_HelloJNI_getCpuInfo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
